export const FOOTER_CONTACT_TITLE = 'Datos de contacto'
export const FOOTER_ADDRESS_TITLE = 'Dirección: '
export const FOOTER_PHONE_TITLE = 'Teléfono: '
export const FOOTER_HOURS_TITLE = 'Horario de atención: '
export const FOOTER_ADDRESS = 'Calle 12 AA Sur # 55D - 30, Medellín'
export const FOOTER_PHONE = '(+57) 314 2829044'
export const FOOTER_HOURS = '08:00 - 20:00, Lun - Dom'
export const FOLLOW_US_TITLE = 'Síguenos'

export const FOOTER_ABOUT_TITLE = 'Más información'
export const FOOTER_ABOUT_LINK1 = 'Sobre nosotros'
export const FOOTER_ABOUT_LINK2 = 'Información de entrega'
export const FOOTER_ABOUT_LINK3 = 'Política de privacidad'
export const FOOTER_ABOUT_LINK4 = 'Términos y condiciones'
export const FOOTER_ABOUT_LINK5 = 'Contáctanos'

export const FOOTER_MYACCOUNT_TITLE = 'Mi cuenta'
export const FOOTER_MYACCOUNT_LINK1 = 'Iniciar sesión'
export const FOOTER_MYACCOUNT_LINK2 = 'Ver carrito'
export const FOOTER_MYACCOUNT_LINK3 = 'Mi lista de deseos'
export const FOOTER_MYACCOUNT_LINK4 = 'Rastrear mi pedido'
export const FOOTER_MYACCOUNT_LINK5 = 'Ayuda'

export const FOOTER_INSTALL_TITLE = '¡Pronto nuestras aplicaciones!'
export const FOOTER_INSTALL_PARAGRAPH = 'Desde App Store o Google Play'
export const FOOTER_INSTALL_PAYMENTS_TEXT = 'Pasarelas de pago seguras'
