export const FOOTER_CONTACT_TITLE = 'Contact'
export const FOOTER_ADDRESS_TITLE = 'Address: '
export const FOOTER_PHONE_TITLE = 'Phone: '
export const FOOTER_HOURS_TITLE = 'Hours: '
export const FOOTER_ADDRESS = 'Calle 12 AA Sur # 55D - 30, Medellín'
export const FOOTER_PHONE = '(+57) 314 2829044'
export const FOOTER_HOURS = '08:00 - 20:00, Mon - Sun'
export const FOLLOW_US_TITLE = 'Follow us'

export const FOOTER_ABOUT_TITLE = 'About'
export const FOOTER_ABOUT_LINK1 = 'About us'
export const FOOTER_ABOUT_LINK2 = 'Delivery Information'
export const FOOTER_ABOUT_LINK3 = 'Privacy Policy'
export const FOOTER_ABOUT_LINK4 = 'Terms & Conditions'
export const FOOTER_ABOUT_LINK5 = 'Contact us'

export const FOOTER_MYACCOUNT_TITLE = 'My Account'
export const FOOTER_MYACCOUNT_LINK1 = 'Sign In'
export const FOOTER_MYACCOUNT_LINK2 = 'View Cart'
export const FOOTER_MYACCOUNT_LINK3 = 'My Wishlist'
export const FOOTER_MYACCOUNT_LINK4 = 'Track My Order'
export const FOOTER_MYACCOUNT_LINK5 = 'Help'

export const FOOTER_INSTALL_TITLE = 'Our Apps Soon!'
export const FOOTER_INSTALL_PARAGRAPH = 'From App Store or Google Play'
export const FOOTER_INSTALL_PAYMENTS_TEXT = 'Secured Payment Gateways'
